from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph.state import CompiledStateGraph
from langgraph.checkpoint.memory import MemorySaver
from langchain_ollama.chat_models import ChatOllama
from langgraph_supervisor import create_supervisor
from langgraph.prebuilt import create_react_agent
from langgraph.errors import GraphRecursionError
from langchain_core.messages import AnyMessage
from langgraph.graph import StateGraph, START
from langchain_groq import ChatGroq

import os

from .backend import State, BasicToolNode, route_tools, plot_agent_schema
from .tools import load_tavily_search_tool, get_spark_sql_tools
from ..prompts.spark_sql import SYSTEM_PROMPT as SPARK_SQL_SYS_PROMPT
from ..load_config import LoadToolsConfig

TOOLS_CFG = LoadToolsConfig()

CATALOG = os.environ.get("UC_CATALOG_NAME", "tpch")
SCHEMA = os.environ.get("UC_SCHEMA_NAME", "bronze")

def build_graph() -> CompiledStateGraph:
    """Builds a graph with multi-agent supervisor architecture"""

    # spark_sql_agent_llm = ChatGroq(model=TOOLS_CFG.spark_sql_agent_llm, temperature=TOOLS_CFG.spark_sql_agent_llm_temperature)
    spark_sql_agent_llm = ChatOllama(model="gpt-oss:120b-cloud", temperature=TOOLS_CFG.spark_sql_agent_llm_temperature) #NOTE local dev
    spark_sql_tools = get_spark_sql_tools(spark_sql_agent_llm)

    spark_sql_agent_prompt = ChatPromptTemplate([
            ("system", SPARK_SQL_SYS_PROMPT.format(**{"CATALOG_NAME": CATALOG, "SCHEMA_NAME": SCHEMA})),
            ("placeholder", "{messages}"),
            ("placeholder", "{agent_scratchpad}"),
    ])

    spark_sql_agent = create_react_agent(model=spark_sql_agent_llm, tools=spark_sql_tools, prompt=spark_sql_agent_prompt, name=TOOLS_CFG.spark_sql_agent_name)

    # supervisor_llm = ChatGroq(model=TOOLS_CFG.supervisor_agent_llm, temperature=TOOLS_CFG.supervisor_agent_llm_temperature)
    supervisor_llm = ChatOllama(model="gpt-oss:120b-cloud", temperature=TOOLS_CFG.supervisor_agent_llm_temperature) #NOTE local dev
    search_tool = load_tavily_search_tool(TOOLS_CFG.tavily_search_max_results)
    
    supervisor = create_supervisor(
        model=supervisor_llm,
        agents=[spark_sql_agent],
        tools=[search_tool],
        prompt=(
            "You are a supervisor managing one agent:\n"
            "- a spark sql agent. Assign Spark SQL query related tasks to this agent\n"
            "Assign work to one agent at a time, do not call agents in parallel.\n"
            "Analyze the final results generated by the agents and display them to the user.\n"
            "IMPORTANT: Do not do any work yourself."
        ),
        add_handoff_back_messages=True,
        output_mode="full_history",
        parallel_tool_calls=False,
        supervisor_name=TOOLS_CFG.supervisor_agent_name,
    )

    memory = MemorySaver()
    graph = supervisor.compile(checkpointer=memory)
    plot_agent_schema(graph)
    return graph
